#!/usr/bin/env bash
# .rddf/sync_strategy_status.sh
# 从 openspec changes (active + archived) 与 initiative YAML
# 派生 .rddf/roadmap/strategy.md §7 状态总表 (migrated 2026-10-09 from tools/sync_strategy_status.sh)
#
# ⚠️ 迁移期 (2026-10-09 - 2026-10-16):
#   老 `tools/sync_strategy_status.sh` 仍写入老路径, 跑两个 --dry-run 输出一致后废弃老脚本
#
# 行为: --dry-run (仅打印) | --json (JSON 输出) | 默认 atomic 写入 §7
# 退出码: 0=成功, 1=openspec 缺失, 2=markdown 缺失, 3=marker 丢失
#
# SSOT 纪律:
#   - §7 表格由本脚本派生 (marker BEGIN/END 之间)
#   - initiative 关联通过 change proposal.md frontmatter 的 `initiative:` 字段

set -euo pipefail

# === 配置 ===
CONTEXT_STORE="chipforge"
STRATEGY_DOC=".rddf/roadmap/strategy.md"
CHANGES_DIR="openspec/changes"
ARCHIVE_DIR="openspec/changes/archive"
INITIATIVES_DIR="$HOME/.local/share/openspec/context-stores/$CONTEXT_STORE/initiatives"
MARKER_BEGIN="<!-- AUTO-GENERATED by .rddf/sync_strategy_status.sh — do not edit -->"
MARKER_END="<!-- end AUTO-GENERATED -->"

# 通用 warn 函数 (校验段用)
warn() { echo "⚠️  $*" >&2; }

DRY_RUN=false
JSON_OUTPUT=false
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
elif [[ "${1:-}" == "--json" ]]; then
  JSON_OUTPUT=true
fi

# === 前置检查 ===
command -v openspec >/dev/null 2>&1 || { echo "ERROR: openspec CLI not found" >&2; exit 1; }
[[ -f "$STRATEGY_DOC" ]] || { echo "ERROR: $STRATEGY_DOC not found" >&2; exit 2; }
[[ -d "$CHANGES_DIR" ]] || { echo "ERROR: $CHANGES_DIR not found" >&2; exit 2; }

# === 收集函数 ===

# extract_frontmatter_field: 从 markdown frontmatter 或 YAML 提取字段值
# 用法: extract_frontmatter_field <file> <key>
# 支持两种格式: (a) markdown frontmatter `---key: value---`, (b) 裸 YAML `key: value`
extract_frontmatter_field() {
  local file="$1"
  local key="$2"
  awk -v key="$key" '
    BEGIN { in_fm = 0; fm_seen = 0 }
    /^---$/ { in_fm = !in_fm; if (in_fm == 1) fm_seen = 1; next }
    {
      # 匹配 key: value (key 必须是一行的第一个字段)
      if ($1 == key":") {
        sub(/^[^:]+:[ \t]*/, "", $0)
        print $0
        exit
      }
    }
  ' "$file"
}

# count_tasks: 统计 tasks.md 中 open/done 数量
# 只统计 "## Acceptance" 段之前的 [x]/[ ] (避免假验收污染)
# 输出: "<open> <done>"
count_tasks() {
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "0 0"
    return
  fi
  # 用 awk 只统计 Acceptance 段之前的内容, 避免 [x] 假验收污染 status
  local open done
  open=$(awk '/^## Acceptance/{exit} /^- \[ \]/{count++} END{print count+0}' "$file" | tr -d '\n')
  open="${open:-0}"
  done=$(awk '/^## Acceptance/{exit} /^- \[x\]/{count++} END{print count+0}' "$file" | tr -d '\n')
  done="${done:-0}"
  echo "${open} ${done}"
}

# compute_change_status: 根据 tasks.md 计算 change 状态
# 输出: TODO | IN_PROGRESS | DONE
compute_change_status() {
  local tasks_file="$1"
  local fm_status="$2"
  local open done
  read -r open done <<< "$(count_tasks "$tasks_file")"
  total=$((open + done))
  if [[ "$fm_status" == "completed" || "$fm_status" == "completed-ahead-of-schedule" || "$fm_status" == "DONE" ]]; then
    echo "DONE"
  elif [[ $total -eq 0 ]]; then
    echo "TODO"
  elif [[ $done -eq 0 ]]; then
    echo "TODO"
  elif [[ $open -eq 0 ]]; then
    echo "DONE"
  else
    echo "IN_PROGRESS ($done/$total)"
  fi
}

# collect_changes: 收集所有 openspec changes (active + archived)
# 输出: 临时文件中每行格式: "change_name|initiative|priority|status|done/total|tasks_path"
collect_changes() {
  local tmpfile="$1"
  > "$tmpfile"

  # Active changes
  for change_dir in "$CHANGES_DIR"/*/; do
    [[ -d "$change_dir" ]] || continue
    local change_name
    change_name=$(basename "$change_dir")
    # 跳过 archive 子目录
    [[ "$change_name" == "archive" ]] && continue
    local proposal="$change_dir/proposal.md"
    [[ -f "$proposal" ]] || continue

    local initiative priority fm_status
    initiative=$(extract_frontmatter_field "$proposal" "initiative" || echo "")
    priority=$(extract_frontmatter_field "$proposal" "priority" || echo "")
    fm_status=$(extract_frontmatter_field "$proposal" "status" || echo "")

    local tasks_file="$change_dir/tasks.md"
    local status
    status=$(compute_change_status "$tasks_file" "$fm_status")
    local counts
    counts=$(count_tasks "$tasks_file")
    echo "$change_name|$initiative|$priority|$status|$counts" >> "$tmpfile"
  done

  # Archived changes (for historical tracking)
  for change_dir in "$ARCHIVE_DIR"/*/; do
    [[ -d "$change_dir" ]] || continue
    local change_name
    change_name=$(basename "$change_dir")
    local proposal="$change_dir/proposal.md"
    [[ -f "$proposal" ]] || continue

    local initiative priority fm_status
    initiative=$(extract_frontmatter_field "$proposal" "initiative" || echo "")
    priority=$(extract_frontmatter_field "$proposal" "priority" || echo "")
    fm_status=$(extract_frontmatter_field "$proposal" "status" || echo "DONE (archived)")

    local tasks_file="$change_dir/tasks.md"
    local status
    # archived changes 默认 DONE 除非 frontmatter 显式声明
    status=$(compute_change_status "$tasks_file" "DONE")
    local counts
    counts=$(count_tasks "$tasks_file")
    echo "$change_name|$initiative|$priority|$status|$counts|ARCHIVED" >> "$tmpfile"
  done
}

# get_initiative_status: 从 initiative YAML 读取 status 字段
get_initiative_status() {
  local init_id="$1"
  local yaml="$INITIATIVES_DIR/$init_id/initiative.yaml"
  if [[ ! -f "$yaml" ]]; then
    echo "UNKNOWN"
    return
  fi
  extract_frontmatter_field "$yaml" "status" || echo "exploring"
}

# === 收集阶段 ===
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
collect_changes "$TMPFILE"

if $JSON_OUTPUT; then
  echo "{"
  echo '  "synced_at": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",'
  echo '  "initiatives": ['
  first=1
  for init_dir in "$INITIATIVES_DIR"/*/; do
    [[ -d "$init_dir" ]] || continue
    init_id=$(basename "$init_dir")
    init_status=$(get_initiative_status "$init_id")
    [[ $first -eq 1 ]] && first=0 || echo ","
    printf '    {"id": "%s", "status": "%s", "changes": [' "$init_id" "$init_status"
    cfirst=1
    while IFS='|' read -r cn ci cp cs cc cm; do
      [[ "$ci" == "$init_id" ]] || continue
      [[ $cfirst -eq 1 ]] && cfirst=0 || printf ','
      printf '{"name": "%s", "status": "%s", "tasks": "%s"}' "$cn" "$cs" "$cc"
    done < "$TMPFILE"
    echo "]}"
  done
  echo '  ]'
  echo "}"
  exit 0
fi

echo "📊 Syncing strategy status from openspec changes"
echo "   Context store: $CONTEXT_STORE"
echo "   Changes dir: $CHANGES_DIR (active + $ARCHIVE_DIR)"
echo ""

# === 输出当前每个 initiative 状态 ===
echo "=== Initiative Status ==="
for init_dir in "$INITIATIVES_DIR"/*/; do
  [[ -d "$init_dir" ]] || continue
  init_id=$(basename "$init_dir")
  init_status=$(get_initiative_status "$init_id")
  echo "[$init_status] $init_id"

  while IFS='|' read -r cn ci cp cs cc cm; do
    [[ "$ci" == "$init_id" ]] || continue
    archive_marker="${cm:-}"
    if [[ "$archive_marker" == "ARCHIVED" ]]; then
      echo "    ✅ [archived] $cn: $cs ($cc)"
    else
      echo "    📋 $cn: $cs ($cc)"
    fi
  done < "$TMPFILE"
done
echo ""

# === 派生 §7 表格 ===
TABLE_TMP=$(mktemp)
trap 'rm -f "$TMPFILE" "$TABLE_TMP"' EXIT

# 表格 header
cat > "$TABLE_TMP" <<'EOF'
| Change | Initiative | Priority | Status | Tasks |
|--------|-----------|----------|--------|-------|
EOF

# 动态遍历所有 initiative (Oracle 审查修订: 不硬编码)
# 按 initiative ID 字母序排序, 保证表格顺序稳定
for init_dir in "$INITIATIVES_DIR"/*/; do
  [[ -d "$init_dir" ]] || continue
  init_id=$(basename "$init_dir")
  while IFS='|' read -r cn ci cp cs cc cm; do
    [[ "$ci" == "$init_id" ]] || continue
    archive_marker="${cm:-}"
    if [[ "$archive_marker" == "ARCHIVED" ]]; then
      status_display="✅ $cs (archived)"
    else
      status_display="$cs"
    fi
    echo "| \`$cn\` | $ci | $cp | $status_display | $cc |" >> "$TABLE_TMP"
  done < "$TMPFILE"
done

# 表格 footer
cat >> "$TABLE_TMP" <<'EOF'

> **Status 解读**:
> - `TODO`: tasks.md 全部 open 或不存在
> - `IN_PROGRESS (N/M)`: 部分完成
> - `DONE`: tasks.md 全部 checked
> - `✅ DONE (archived)`: 已 archive 到 `openspec/changes/archive/`
EOF

if $DRY_RUN; then
  echo "🔍 DRY-RUN: $STRATEGY_DOC §7 would be re-derived (not modified)"
  echo ""
  echo "=== Proposed §7 content ==="
  cat "$TABLE_TMP"
  echo "============================="
  echo ""
  # 继续走完脚本以运行 Initiative 一致性校验 (只读操作, dry-run 安全)
fi

# === atomic 写入 strategy doc §7 ===
DOC_TMP="${STRATEGY_DOC}.tmp"
DOC_BAK="${STRATEGY_DOC}.bak"

# ⚠️ CRITICAL 数据丢失防护 (Metis #5 审查修订)
# 1. 修改前先备份
cp "$STRATEGY_DOC" "$DOC_BAK"
# 2. 用 awk 替换 marker 之间的内容
# 3. 替换后验证 marker 仍存在 (防止整文件被截断)

# 宽松匹配: 子串匹配 (兼容空格/破折差异)
awk -v marker_begin="$MARKER_BEGIN" -v marker_end="$MARKER_END" -v table_file="$TABLE_TMP" '
  BEGIN {
    in_block = 0
    while ((getline line < table_file) > 0) {
      table_content = table_content line "\n"
    }
    close(table_file)
  }
  index($0, marker_begin) > 0 {
    print
    print ""
    printf "%s", table_content
    in_block = 1
    next
  }
  index($0, marker_end) > 0 {
    if (in_block) {
      print
      in_block = 0
      next
    }
  }
  in_block { next }
  { print }
' "$STRATEGY_DOC" > "$DOC_TMP"

# ⚠️ 数据完整性验证 (Metis #5 审查修订)
if ! grep -q "$MARKER_BEGIN" "$DOC_TMP" || ! grep -q "$MARKER_END" "$DOC_TMP"; then
  echo "ERROR: marker lost during rewrite, restoring from backup" >&2
  mv "$DOC_BAK" "$STRATEGY_DOC"
  rm -f "$DOC_TMP"
  exit 3
fi

# 验证后移除备份
mv "$DOC_TMP" "$STRATEGY_DOC"
rm -f "$DOC_BAK"

if ! $DRY_RUN; then
  echo "✅ $STRATEGY_DOC §7 updated"
  echo ""
fi

# === Initiative 一致性校验 (migrated 2026-10-09 选项 D 混合方案) ===
# 验证 XDG initiative 状态 vs strategy.md §3 表格的双 SSOT 漂移
# XDG 权威: ~/.local/share/openspec/context-stores/chipforge/initiatives/*/initiative.yaml
# rdd-workflow 显示: .rddf/roadmap/strategy.md §3
# 漂移检测: 不一致时 warn (不强制同步, XDG 仍权威, 人工决议)
echo "=== Initiative 一致性校验 (XDG vs strategy.md §3) ==="

# status 枚举模糊匹配表 (XDG 受控枚举 ↔ strategy.md 自由文本)
# XDG: archived | exploring | partially_completed | active | deferred
declare -A STATUS_ALIAS
STATUS_ALIAS[archived]="已收官|archived|✅"
STATUS_ALIAS[exploring]="占位|exploring|⏸|deferred|🟡 部分"
STATUS_ALIAS[partially_completed]="部分收官|partially_completed|partially"
STATUS_ALIAS[active]="active|活跃|active \\(|启动期|🔄"
STATUS_ALIAS[deferred]="deferred|推迟|⏸ deferred|远期"

DRIFT_FOUND=0
if [[ -d "$INITIATIVES_DIR" ]]; then
  for init_dir in "$INITIATIVES_DIR"/*/; do
    [[ -d "$init_dir" ]] || continue
    init_id=$(basename "$init_dir")
    init_yaml="$init_dir/initiative.yaml"
    [[ -f "$init_yaml" ]] || continue
    init_status=$(awk -v key="status" '
      /^[[:space:]]*status:[[:space:]]*/ { sub(/^[[:space:]]*status:[[:space:]]*/, ""); print; exit }
    ' "$init_yaml")
    [[ -z "$init_status" ]] && init_status="UNKNOWN"

    # 从 strategy.md §3 表格读对应行
    strategy_line=$(grep -F "| \`$init_id\` |" "$STRATEGY_DOC" | head -1)
    if [[ -z "$strategy_line" ]]; then
      warn "initiative $init_id 在 XDG 存在但 strategy.md §3 缺失 (XDG status=$init_status)"
      DRIFT_FOUND=$((DRIFT_FOUND + 1))
      continue
    fi

    # 模糊匹配 (XDG 受控枚举 ↔ strategy.md 自由文本)
    pattern="${STATUS_ALIAS[$init_status]:-$init_status}"
    if ! echo "$strategy_line" | grep -qE "$pattern"; then
      warn "drift: initiative $init_id XDG status=$init_status 但 strategy.md §3 表格未匹配 (pattern: $pattern)"
      echo "    strategy: $strategy_line"
      DRIFT_FOUND=$((DRIFT_FOUND + 1))
    fi
  done
else
  warn "XDG initiatives dir 不存在: $INITIATIVES_DIR (跳过校验, 视为首次运行)"
fi

if [[ $DRIFT_FOUND -gt 0 ]]; then
  echo ""
  echo "⚠️  发现 $DRIFT_FOUND 处 initiative 漂移 (XDG vs strategy.md §3)"
  echo "   XDG 权威 — 写 initiative 状态走: openspec initiative edit <id> --store chipforge"
  echo "   rdd-workflow 显示: .rddf/roadmap/strategy.md §3 表格 (本节为展示用, 不强制同步)"
  echo "   修复: 改 XDG 后跑本脚本, 表格由 §7 sync 派生不变; §3 表格由人工维护"
fi
echo ""
echo "📋 Run \`git diff $STRATEGY_DOC\` to review changes"
